{"name": "test_04", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_demo2.TestCase object at 0x00000264CEBEA4D0>\n\n    def test_04(self):\n        print(\"---用例4执行---\")\n>       assert False\nE       assert False\n\ntestcase\\test_demo2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "69a6a88f-9ec4-469b-9719-53199661b285-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "32776331-d90e-4bfa-aeec-4f712e2970af-attachment.txt", "type": "text/plain"}], "start": 1753974848269, "stop": 1753974848269, "uuid": "dc17cc34-1175-4158-b4bf-94c44aa2fefe", "historyId": "02490a258f3e4624d2a5c9b5a01c2c00", "testCaseId": "02490a258f3e4624d2a5c9b5a01c2c00", "fullName": "testcase.test_demo2.TestCase#test_04", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo2"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "BF-202006262120"}, {"name": "thread", "value": "7116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo2"}]}