{"name": "test_04", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_demo2.TestCase object at 0x00000264CEBEA4D0>\n\n    def test_04(self):\n        print(\"---用例4执行---\")\n>       assert False\nE       assert False\n\ntestcase\\test_demo2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "8b095afc-3c41-4c96-abfd-aecbb88defae-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "344c4d8e-39ec-453b-9201-88d8f233aa60-attachment.txt", "type": "text/plain"}], "start": 1753974849277, "stop": 1753974849277, "uuid": "ba31d4e0-a665-4ff1-b15f-329ad153725f", "historyId": "02490a258f3e4624d2a5c9b5a01c2c00", "testCaseId": "02490a258f3e4624d2a5c9b5a01c2c00", "fullName": "testcase.test_demo2.TestCase#test_04", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo2"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "BF-202006262120"}, {"name": "thread", "value": "7116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo2"}]}