{"name": "test_04", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <testcase.test_demo2.TestCase object at 0x00000264CEBEA4D0>\n\n    def test_04(self):\n        print(\"---用例4执行---\")\n>       assert False\nE       assert False\n\ntestcase\\test_demo2.py:38: AssertionError"}, "attachments": [{"name": "log", "source": "1576e8c1-252c-4d8e-90d1-e436f74c1e5b-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "7222e458-9143-4923-a7b6-aaa7e54a9667-attachment.txt", "type": "text/plain"}], "start": 1753974847261, "stop": 1753974847262, "uuid": "090c247f-d812-45bc-930c-3e87e55b217d", "historyId": "02490a258f3e4624d2a5c9b5a01c2c00", "testCaseId": "02490a258f3e4624d2a5c9b5a01c2c00", "fullName": "testcase.test_demo2.TestCase#test_04", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_demo2"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "BF-202006262120"}, {"name": "thread", "value": "7116-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_demo2"}]}